In [1]:
import pandas as pd
import numpy as np
import math

In [4]:
asset = pd.read_excel(R'C:\Users\20001009\multi_asset_etf_data.xlsx', sheet_name = 'excess returns')
del asset["Date"]
ac = asset.cov()
ac

BWX       DBC       EEM       EFA       HYG       IEF       IYR  \
BWX  0.000488  0.000382  0.000750  0.000573  0.000278  0.000118  0.000453   
DBC  0.000382  0.002734  0.001635  0.001407  0.000602 -0.000366  0.000788   
EEM  0.000750  0.001635  0.003110  0.002200  0.001030 -0.000240  0.001778   
EFA  0.000573  0.001407  0.002200  0.002145  0.000867 -0.000244  0.001640   
HYG  0.000278  0.000602  0.001030  0.000867  0.000613 -0.000066  0.000964   
IEF  0.000118 -0.000366 -0.000240 -0.000244 -0.000066  0.000286 -0.000053   
IYR  0.000453  0.000788  0.001778  0.001640  0.000964 -0.000053  0.002784   
PSP  0.000673  0.001599  0.002789  0.002630  0.001263 -0.000320  0.002439   
QAI  0.000193  0.000391  0.000624  0.000540  0.000259 -0.000020  0.000452   
SPY  0.000364  0.001068  0.001707  0.001654  0.000752 -0.000228  0.001581   
TIP  0.000160  0.000052  0.000171  0.000097  0.000076  0.000147  0.000202   

          PSP       QAI       SPY       TIP  
BWX  0.000673  0.000193  0.000364  0.000160  
DBC  0.001599  0.000391  0.001068  0.000052  
EEM  0.002789  0.000624  0.001707  0.000171  
EFA  0.002630  0.000540  0.001654  0.000097  
HYG  0.001263  0.000259  0.000752  0.000076  
IEF -0.000320 -0.000020 -0.000228  0.000147  
IYR  0.002439  0.000452  0.001581  0.000202  
PSP  0.003932  0.000719  0.002311  0.000146  
QAI  0.000719  0.000195  0.000474  0.000067  
SPY  0.002311  0.000474  0.001681  0.000078  
TIP  0.000146  0.000067  0.000078  0.000172

In [6]:
means = np.array([0.0005325,0.003519, 0.006146, 0.007114, 0.006009, 0.0019589, 0.01266, 0.01158, 0.001712, 0.01256, 0.002667])
sd = np.diag(ac, k=0)
sd = np.sqrt(sd)
sd

array([0.02208501, 0.05228876, 0.05576329, 0.04631175, 0.02474899,
       0.01692434, 0.05276007, 0.06270265, 0.01396878, 0.04100405,
       0.0131208 ])

In [7]:
def sharpe(returns):
    sr = returns.mean() / returns.std()
    return sr


In [22]:
sharpe1 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
for i in range(0,11):
    sharpe1[i] = means[i]/sd[i]

[0.024111372835460918,
 0.06729936114917427,
 0.11021588362449437,
 0.15361112931517024,
 0.24279774495212364,
 0.11574450990526283,
 0.23995420614464286,
 0.1846811867514756,
 0.12255901230941398,
 0.30631121677428264,
 0.20326509433021733]

In [17]:
onevec = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
onevec.transpose()
inv_cov = np.linalg.inv(ac)
wt = 1/np.dot(np.dot(onevec.transpose(), inv_cov), means) * np.dot(inv_cov, means)
wt

array([-0.97375555,  0.19186994,  0.1285199 , -0.00739493,  1.30894351,
        2.15855266, -0.36884161, -0.3989305 , -4.33880845,  2.34956402,
        0.950281  ])

In [19]:
wt_mean = np.dot(wt, means)
wt_mean*12

0.33978606127112354

In [13]:
def sigma(wts, data):
    sum = 0
    y = data.cov()
    for j in range(0,11):
        for i in range(0,11):
            x = y.iloc[i,j]
            sum = sum + wts[i]*wts[j]*x
    return math.sqrt(sum)

In [14]:
def sharpe2(mean, wts, data):
    sr = mean / sigma(wts,data)
    return sr

In [15]:
sharpe2(wt_mean, wt, asset)

0.5930533889463918

In [91]:
delta = np.dot(np.dot(onevec.transpose(), inv_cov), means)
delta = delta / np.dot(np.dot(means.transpose(), inv_cov),means)
delta = 0.01 * delta
ws = wt.copy()
ws = delta * ws

In [131]:
sharpe2(0.01, ws, asset)

0.5930533889463928

In [96]:
we = wt.copy()
for i in range(0,11):
    we[i] = 1/11 * 16.55171

array([1.50470091, 1.50470091, 1.50470091, 1.50470091, 1.50470091,
       1.50470091, 1.50470091, 1.50470091, 1.50470091, 1.50470091,
       1.50470091])

In [138]:
sigma(we, asset)
sharpe2(0.01, we, asset)

wr = wt.copy()
for i in range(0,11):
    wr[i] = (1/math.sqrt(ac.iloc[i,i]))/410.515


array([0.11029944, 0.04658677, 0.04368402, 0.05259928, 0.09842681,
       0.14393258, 0.04617061, 0.03884947, 0.17438634, 0.0594079 ,
       0.18565676])

In [139]:
sharpe2(np.dot(wr, means)

0.004312998838268319

In [114]:
asset2 = pd.read_excel('assets.xlsx', sheet_name = 'excess returns')
asset2.set_index('Date',inplace = True)
asset2 = asset2.loc[:'2020-12-31']

inv_cov2 = np.linalg.inv(asset2.cov())
asset2.describe()
means2 = np.array([0.002189,-0.001108,0.008139,0.007913,0.006913,0.003054,0.012687,0.013323,0.002381,0.013095,0.002971])
wt2 = 1/np.dot(np.dot(onevec.transpose(), inv_cov2), means2) * np.dot(inv_cov2, means2)

delta = np.dot(np.dot(onevec.transpose(), inv_cov2), means2)
delta = delta / np.dot(np.dot(means2.transpose(), inv_cov2),means2)
delta = 0.01 * delta
wt2 = delta * wt2

In [133]:
asset3 = pd.read_excel('assets.xlsx', sheet_name = 'excess returns')
asset3.set_index('Date',inplace = True)
asset3 = asset3.loc[:'2021-12-31']
means3 = np.array([0.001446,0.001372,0.007297,0.008039,0.006622,0.002607,0.013938,0.013779,0.002193,0.013780,0.003111])
np.dot(wt2, means)
sharpe2(0.008814239021071698, wt2, asset3)

0.5712302060641821

In [134]:
wt2_mean = np.dot(wt2, means)
sharpe2(wt2_mean, wt2, asset)

0.5109589029130842